spring:
  datasource:
    url: jdbc:oracle:thin:@172.20.51.70:1521/db11
    username: ocp_admin_webapp_admin
    password: admin
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        session:
          events:
            log: LOG_QUERIES_SLOWER_THAN_MS= 25

